### ISSUE TITLE
Settings page does not load on brand new Docker install (js error)

### ISSUE THREAD

**Issue by admazzola** [discourse/discourse_docker#214]
followed this guide:
https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md

Using 1GB server.

Got this in the chrome console:

application-97f53b50d85b6a2d829b3f1f97e5e2a3.js:1
Uncaught TypeError: Cannot read property 'getResponseHeader' of undefined

**Comment by gregawoods** [comment]
We have been hit by this issue as well. It started immediately after doing an `./launder rebuild app`.

Looking at the Rails logs I noticed a couple things:

- Requests were often being redirected to the login page, despite the user being logged in
- Requests with JSON request format were being treated as HTML

This made me wonder if some headers were being lost somehow between the browser and the server. I looked over the docker diffs, and the one thing that stood out to me was the removal of spdy and addition of http2. 

I _think_ I have resolved the issue in my app by disabling http2 in the nginx configuration, though I'd like to see if another party can try it and verify. To test this, remove any references to http2 in the following files and rebuild your app:

- `templates/web.ssl.template.yml`
- `templates/web.socketed.template.yml`

For reference, I was not able to reproduce the issue when using an older browser (Firefox 35). Older browsers are unlikely to support http2, so that would seem to back up my suspicion.

**Comment by admazzola** [comment]
Hmm thanks for looking in to this.  I am still getting the issue even after I just applied to the update.  Here are the contents of those files... I did not change them since I do not see any references to http2

web.socketed.template.yml
run:
  - file:
     path: /etc/runit/1.d/remove-old-socket
     chmod: "+x"
     contents: |
        #!/bin/bash
        rm -f /shared/nginx.http*.sock
  - file:
     path: /etc/runit/3.d/remove-old-socket
     chmod: "+x"
     contents: |
        #!/bin/bash
        rm -f /shared/nginx.http*.sock
  - replace:
     filename: "/etc/nginx/conf.d/discourse.conf"
     from: /listen 80;/
     to: |
       listen unix:/shared/nginx.http.sock;
       set_real_ip_from unix:;
  - replace:
     filename: "/etc/nginx/conf.d/discourse.conf"
     from: /listen 443 ssl http2;/
     to: |
       listen unix:/shared/nginx.https.sock ssl http2;
       set_real_ip_from unix:;

web.ssl.template.yml
run:
  - exec:
     cmd:
       # Generate strong Diffie-Hellman parameters
       - "mkdir -p /shared/ssl/"
       - "[ -e /shared/ssl/dhparams.pem ] || openssl dhparam -out /shared/ssl/dhparams.pem 2048"
  - replace:
     filename: "/etc/nginx/conf.d/discourse.conf"
     from: /server.+{/
     to: |
       server {
         listen 80;
         rewrite ^ https://$$ENV_DISCOURSE_HOSTNAME$request_uri? permanent;
       }
       server {
  - replace:
     filename: "/etc/nginx/conf.d/discourse.conf"
     from: /listen 80;\s+gzip on;/m
     to: |
       listen 443 ssl http2;
       ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
       # courtesy of https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations
       ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
       ssl_prefer_server_ciphers on;

       ssl_certificate /shared/ssl/ssl.crt;
       ssl_certificate_key /shared/ssl/ssl.key;
       ssl_dhparam /shared/ssl/dhparams.pem;

       ssl_session_tickets off;
       ssl_session_timeout 1d;
       ssl_session_cache shared:SSL:1m;

       # remember the certificate for a year and automatically connect to HTTPS for this domain
       add_header Strict-Transport-Security 'max-age=31536000';

       gzip on;

       if ($http_host != $$ENV_DISCOURSE_HOSTNAME) {
          rewrite (.*) https://$$ENV_DISCOURSE_HOSTNAME$1 permanent;
       }
