### ISSUE TITLE
launcher bootstrap doesn't work

### ISSUE THREAD

**Issue by capsu97** [discourse/discourse_docker#306]
Every time I've tried running the setup I get this error
```
cd /pups && git pull && /pups/bin/pups --stdin
fatal: unable to access 'https://github.com/SamSaffron/pups.git/': gnutls_handshake() failed: Error in the pull function.
fd1b71291f40a91dd48b4d20d881c75ca138e0ed8e02ee2502ce347841477e46
** FAILED TO BOOTSTRAP ** 
```
Docker version 1.12.3, build 6b644ec
OS: Debian 8.6

can you help me?

**Comment by SamSaffron** [comment]
Can the host do a git pull from github, this looks like an odd error.

**Comment by capsu97** [comment]
yes, the host can do git pull. I have tried with the same repo

**Comment by edisubaru** [comment]
Hey, got a similar error while trying to update to 1.3.8 on Debian too
`cd /pups && git pull && /pups/bin/pups --stdin
fatal: unable to access 'https://github.com/SamSaffron/pups.git/': Failed to connect to github.com port 443: Connection timed out
d49152690a25cb4f41b725892c24182e2abaa408018b45d4805cbe4584c16183
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one`
I am to clone this repo on a tmp directory without issue !

**Comment by edisubaru** [comment]
Nevermind my last post, the boostrap just worked without changing anything, probably a github server error. Even tho since the last update I got a blank page as home page and in /admin/upgrade it stills tell me to upgrade the docker image (which I just did) but that's another issue (maybe you can create / move this? I don't know that much the github issues system)

**Comment by capsu97** [comment]
Solved it. It was a problem with the mtu value because the server was a openstack instance.
