### ISSUE TITLE
launcher doesn't support linking

### ISSUE THREAD

**Issue by ligthyear** [discourse/discourse_docker#56]
We should add linking support to the launcher.

**Comment by SamSaffron** [comment]
I am fine to add linking support if someone wants to build it into launcher.

**Comment by mc0e** [comment]
I think this probably wants review due to the widespread adoption of docker-compose.

I suspect that discourse should be manageable with just docker-compose, and the launcher might remain as a thin wrapper around it.  Using docker-compose is significant in terms of fitting in with orchestration tools like kubernetes.

**Comment by SamSaffron** [comment]
I will look at reviewing this when moving to pg 9.5, I kind of want
db/redis/web to be the norm for container setup

**Comment by SamSaffron** [comment]
this is supported per: 

https://github.com/discourse/discourse_docker/commit/8b617e6e990a803bc523d95a99f6d02dcd0984a4

not the most elegant format in the world but supported just fine
